export const data = {
  productId: '',
  appData: {
    // 全局state
    dataset: {
      // ...物模型
      // 设备在线/离线
      loading: {
        dataType: 'boolean',
        initValue: true,
      },
    },
    pages: [
      {
        name: 'index',
        nodes: {
          ROOT: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['40', '40', '40', '40'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 255,
                g: 255,
                b: 255,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '800px',
              height: 'auto',
            },
            displayName: 'Container',
            custom: {
              displayName: 'App',
            },
            hidden: false,
            nodes: ['P5pW7ghNsu', '3jerUawxZF', '2KH2GcCDG7'],
            linkedNodes: {},
          },
          P5pW7ghNsu: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'row',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['40', '40', '40', '40'],
              margin: ['0', '0', '40', '0'],
              background: {
                r: 255,
                g: 255,
                b: 255,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '100%',
              height: 'auto',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Introduction',
            },
            parent: 'ROOT',
            hidden: false,
            nodes: ['xfOwoq4P1j', 'AgFxg3BBir'],
            linkedNodes: {},
          },
          xfOwoq4P1j: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['0', '20', '0', '20'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 255,
                g: 255,
                b: 255,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '40%',
              height: '100%',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Heading',
            },
            parent: 'P5pW7ghNsu',
            hidden: false,
            nodes: ['RV7IIN0bFn'],
            linkedNodes: {},
          },
          RV7IIN0bFn: {
            type: {
              resolvedName: 'Text',
            },
            isCanvas: false,
            props: {
              fontSize: '23',
              textAlign: 'left',
              fontWeight: '400',
              color: {
                r: 92,
                g: 90,
                b: 90,
                a: 1,
              },
              margin: [0, 0, 0, 0],
              shadow: 0,
              text:
                'Craft.js is a React framework for building powerful &amp; feature-rich drag-n-drop page editors.',
            },
            displayName: 'Text',
            custom: {},
            parent: 'xfOwoq4P1j',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          AgFxg3BBir: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['0', '20', '0', '20'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 255,
                g: 255,
                b: 255,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '60%',
              height: '100%',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Description',
            },
            parent: 'P5pW7ghNsu',
            hidden: false,
            nodes: ['XkyJJ5USP6'],
            linkedNodes: {},
          },
          XkyJJ5USP6: {
            type: {
              resolvedName: 'Text',
            },
            isCanvas: false,
            props: {
              fontSize: '14',
              textAlign: 'left',
              fontWeight: '400',
              color: {
                r: 92,
                g: 90,
                b: 90,
                a: 1,
              },
              margin: [0, 0, 0, 0],
              shadow: 0,
              text:
                'Everything you see here, including the editor, itself is made of React components. Craft.js comes only with the building blocks for a page editor; it provides a drag-n-drop system and handles the way user components should be rendered, updated and moved, among other things. <br> <br> You control the way your editor looks and behave.',
            },
            displayName: 'Text',
            custom: {},
            parent: 'AgFxg3BBir',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          '3jerUawxZF': {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['40', '40', '40', '40'],
              margin: ['0', '0', '40', '0'],
              background: {
                r: 39,
                g: 41,
                b: 41,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '100%',
              height: 'auto',
            },
            displayName: 'Container',
            custom: {
              displayName: 'ComplexSection',
            },
            parent: 'ROOT',
            hidden: false,
            nodes: ['fU-Wt9zCoN'],
            linkedNodes: {},
          },
          'fU-Wt9zCoN': {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['0', '0', '0', '0'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 76,
                g: 78,
                b: 78,
                a: 0,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '100%',
              height: 'auto',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Wrapper',
            },
            parent: '3jerUawxZF',
            hidden: false,
            nodes: ['iuvABGhW-X', 'd0yUqaKaxG'],
            linkedNodes: {},
          },
          'iuvABGhW-X': {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['0', '0', '0', '0'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 0,
                g: 0,
                b: 0,
                a: 0,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '350px',
              height: '250px',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Square',
            },
            parent: 'fU-Wt9zCoN',
            hidden: false,
            nodes: ['NbKuy-fFz4'],
            linkedNodes: {},
          },
          'NbKuy-fFz4': {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              fillSpace: 'no',
              padding: ['10', '20', '10', '20'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 76,
                g: 78,
                b: 78,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 25,
              radius: 0,
              width: '90%',
              height: '90%',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Outer',
            },
            parent: 'iuvABGhW-X',
            hidden: false,
            nodes: ['vs6YS13xxR'],
            linkedNodes: {},
          },
          vs6YS13xxR: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              fillSpace: 'no',
              padding: ['10', '20', '10', '20'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 76,
                g: 78,
                b: 78,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 50,
              radius: 0,
              width: '80%',
              height: '80%',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Middle',
            },
            parent: 'NbKuy-fFz4',
            hidden: false,
            nodes: ['yFraPEVxrI'],
            linkedNodes: {},
          },
          yFraPEVxrI: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              fillSpace: 'no',
              padding: ['10', '20', '10', '20'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 76,
                g: 78,
                b: 78,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 50,
              radius: 0,
              width: '60%',
              height: '60%',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Inner',
            },
            parent: 'vs6YS13xxR',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          d0yUqaKaxG: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'yes',
              padding: ['0', '0', '0', '20'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 0,
                g: 0,
                b: 0,
                a: 0,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '55%',
              height: '100%',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Content',
            },
            parent: 'fU-Wt9zCoN',
            hidden: false,
            nodes: ['XkcZdrzOeR', '4dA1raPgHk'],
            linkedNodes: {},
          },
          XkcZdrzOeR: {
            type: {
              resolvedName: 'Text',
            },
            isCanvas: false,
            props: {
              fontSize: '20',
              textAlign: 'left',
              fontWeight: '500',
              color: {
                r: '255',
                g: '255',
                b: '255',
                a: '1',
              },
              margin: ['0', '0', '18', '0'],
              shadow: 0,
              text: 'Design complex components',
            },
            displayName: 'Text',
            custom: {},
            parent: 'd0yUqaKaxG',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          '4dA1raPgHk': {
            type: {
              resolvedName: 'Text',
            },
            isCanvas: false,
            props: {
              fontSize: '14',
              textAlign: 'left',
              fontWeight: '400',
              color: {
                r: '255',
                g: '255',
                b: '255',
                a: '0.8',
              },
              margin: [0, 0, 0, 0],
              shadow: 0,
              text:
                'You can define areas within your React component which users can drop other components into. <br/><br />You can even design how the component should be edited — content editable, drag to resize, have inputs on toolbars — anything really.',
            },
            displayName: 'Text',
            custom: {},
            parent: 'd0yUqaKaxG',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          '2KH2GcCDG7': {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['40', '40', '40', '40'],
              margin: ['0', '0', '40', '0'],
              background: {
                r: 234,
                g: 245,
                b: 245,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '100%',
              height: 'auto',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Programmatic',
            },
            parent: 'ROOT',
            hidden: false,
            nodes: ['C9a3LGVqG9', 'P4gvEM3g8C'],
            linkedNodes: {},
          },
          C9a3LGVqG9: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['0', '0', '0', '0'],
              margin: ['0,', '0', '20', '0'],
              background: {
                r: 76,
                g: 78,
                b: 78,
                a: 0,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '100%',
              height: 'auto',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Heading',
            },
            parent: '2KH2GcCDG7',
            hidden: false,
            nodes: ['zmNy5AaMpq', 'KYbkABWSct'],
            linkedNodes: {},
          },
          zmNy5AaMpq: {
            type: {
              resolvedName: 'Text',
            },
            isCanvas: false,
            props: {
              fontSize: '23',
              textAlign: 'left',
              fontWeight: '500',
              color: {
                r: '46',
                g: '47',
                b: '47',
                a: '1',
              },
              margin: [0, 0, 0, 0],
              shadow: 0,
              text: 'Programmatic drag & drop',
            },
            displayName: 'Text',
            custom: {},
            parent: 'C9a3LGVqG9',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          KYbkABWSct: {
            type: {
              resolvedName: 'Text',
            },
            isCanvas: false,
            props: {
              fontSize: '14',
              textAlign: 'left',
              fontWeight: '400',
              color: {
                r: 92,
                g: 90,
                b: 90,
                a: 1,
              },
              margin: [0, 0, 0, 0],
              shadow: 0,
              text: 'Govern what goes in and out of your components',
            },
            displayName: 'Text',
            custom: {},
            parent: 'C9a3LGVqG9',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          P4gvEM3g8C: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'row',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['0', '0', '0', '0'],
              margin: ['30', '0', '0', '0'],
              background: {
                r: 76,
                g: 78,
                b: 78,
                a: 0,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '100%',
              height: 'auto',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Content',
            },
            parent: '2KH2GcCDG7',
            hidden: false,
            nodes: ['sJ1bzVNItL', 'Zi0IaUUeko'],
            linkedNodes: {},
          },
          sJ1bzVNItL: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'row',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['0', '20', '0', '0'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 0,
                g: 0,
                b: 0,
                a: 0,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '45%',
              height: 'auto',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Left',
            },
            parent: 'P4gvEM3g8C',
            hidden: false,
            nodes: ['3Qr1ApfXI7'],
            linkedNodes: {},
          },
          '3Qr1ApfXI7': {
            type: {
              resolvedName: 'Custom1',
            },
            isCanvas: false,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['20', '20', '20', '20'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 119,
                g: 219,
                b: 165,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 40,
              radius: 0,
              width: '100%',
              height: 'auto',
            },
            displayName: 'Custom 1',
            custom: {},
            parent: 'sJ1bzVNItL',
            hidden: false,
            nodes: [],
            linkedNodes: {
              wow: 'vr-2L-_y2J',
            },
          },
          Zi0IaUUeko: {
            type: {
              resolvedName: 'Container',
            },
            isCanvas: true,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['0', '0', '0', '20'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 0,
                g: 0,
                b: 0,
                a: 0,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 0,
              radius: 0,
              width: '55%',
              height: 'auto',
            },
            displayName: 'Container',
            custom: {
              displayName: 'Right',
            },
            parent: 'P4gvEM3g8C',
            hidden: false,
            nodes: ['dLHytx0ybf', 'Nd4bYu74Qr'],
            linkedNodes: {},
          },
          dLHytx0ybf: {
            type: {
              resolvedName: 'Custom2',
            },
            isCanvas: false,
            props: {
              flexDirection: 'row',
              alignItems: 'center',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['0', '0', '0', '20'],
              margin: ['0', '0', '0', '0'],
              background: {
                r: 108,
                g: 126,
                b: 131,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 40,
              radius: 0,
              width: '100%',
              height: '125px',
            },
            displayName: 'Custom 2',
            custom: {},
            parent: 'Zi0IaUUeko',
            hidden: false,
            nodes: [],
            linkedNodes: {
              wow: 'WzU8iGcMtv',
            },
          },
          Nd4bYu74Qr: {
            type: {
              resolvedName: 'Custom3',
            },
            isCanvas: false,
            props: {
              flexDirection: 'column',
              alignItems: 'flex-start',
              justifyContent: 'flex-start',
              fillSpace: 'no',
              padding: ['20', '20', '20', '20'],
              margin: ['20', '0', '0', '0'],
              background: {
                r: 134,
                g: 187,
                b: 201,
                a: 1,
              },
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
              shadow: 40,
              radius: 0,
              width: '100%',
              height: 'auto',
            },
            displayName: 'Custom 3',
            custom: {},
            parent: 'Zi0IaUUeko',
            hidden: false,
            nodes: [],
            linkedNodes: {
              wow: 'QEwJmGj9gy',
            },
          },
          'vr-2L-_y2J': {
            type: {
              resolvedName: 'OnlyButtons',
            },
            isCanvas: true,
            props: {},
            displayName: 'OnlyButtons',
            custom: {},
            parent: '3Qr1ApfXI7',
            hidden: false,
            nodes: ['3ykCtXivH7', 'LE15Gphjg_'],
            linkedNodes: {},
          },
          '3ykCtXivH7': {
            type: {
              resolvedName: 'Button',
            },
            isCanvas: false,
            props: {
              style: {
                // backgroundColor: 'black',
              },
              color: {
                r: 92,
                g: 90,
                b: 90,
                a: 1,
              },
              buttonStyle: 'full',
              text: 'Button',
              margin: ['5', '0', '5', '0'],
              textComponent: {
                fontSize: '15',
                textAlign: 'center',
                fontWeight: '500',
                color: {
                  r: 92,
                  g: 90,
                  b: 90,
                  a: 1,
                },
                margin: [0, 0, 0, 0],
                shadow: 0,
                text: 'Text 123',
              },
              ':loading': '$app.dataset.loading',
            },
            displayName: 'Button',
            custom: {
              listeners: [
                {
                  id: 'wa2q1c9f8e1',
                  eventName: 'tap',
                  type: 'platform',
                  handler: {
                    name: 'showModal',
                    module: 'platform',
                    params: {
                      cancelColor: '#000000',
                      cancelText: '取消',
                      confirmColor: '#576B95',
                      confirmText: '确认',
                      content: '请输入弹窗内容',
                      showCancel: true,
                      title: '弹窗标题',
                    },
                  },
                },
              ],
            },
            parent: 'vr-2L-_y2J',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          LE15Gphjg_: {
            type: {
              resolvedName: 'Button',
            },
            isCanvas: false,
            props: {
              background: {
                r: 255,
                g: 255,
                b: 255,
                a: 0.5,
              },
              color: {
                r: 255,
                g: 255,
                b: 255,
                a: 1,
              },
              buttonStyle: 'outline',
              text: 'Button',
              margin: ['5', '0', '5', '0'],
              textComponent: {
                fontSize: '15',
                textAlign: 'center',
                fontWeight: '500',
                color: {
                  r: 92,
                  g: 90,
                  b: 90,
                  a: 1,
                },
                margin: [0, 0, 0, 0],
                shadow: 0,
                text: 'Text',
              },
            },
            displayName: 'Button',
            custom: {},
            parent: 'vr-2L-_y2J',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          WzU8iGcMtv: {
            type: {
              resolvedName: 'Custom2VideoDrop',
            },
            isCanvas: true,
            props: {},
            displayName: 'Custom2VideoDrop',
            custom: {},
            parent: 'dLHytx0ybf',
            hidden: false,
            nodes: ['N5nvY5pTD8'],
            linkedNodes: {},
          },
          N5nvY5pTD8: {
            type: {
              resolvedName: 'Video',
            },
            isCanvas: false,
            props: {
              videoId: 'IwzUs1IMdyQ',
            },
            displayName: 'Video',
            custom: {},
            parent: 'WzU8iGcMtv',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
          QEwJmGj9gy: {
            type: {
              resolvedName: 'Custom3BtnDrop',
            },
            isCanvas: true,
            props: {},
            displayName: 'Custom3BtnDrop',
            custom: {},
            parent: 'Nd4bYu74Qr',
            hidden: false,
            nodes: ['noyVNQCaoX'],
            linkedNodes: {},
          },
          noyVNQCaoX: {
            type: {
              resolvedName: 'Button',
            },
            isCanvas: false,
            props: {
              background: {
                r: 184,
                g: 247,
                b: 247,
                a: 1,
              },
              color: {
                r: 92,
                g: 90,
                b: 90,
                a: 1,
              },
              buttonStyle: 'full',
              text: 'Button',
              margin: ['5', '0', '5', '0'],
              textComponent: {
                fontSize: '15',
                textAlign: 'center',
                fontWeight: '500',
                color: {
                  r: 92,
                  g: 90,
                  b: 90,
                  a: 1,
                },
                margin: [0, 0, 0, 0],
                shadow: 0,
                text: 'Text',
              },
            },
            displayName: 'Button',
            custom: {},
            parent: 'QEwJmGj9gy',
            hidden: false,
            nodes: [],
            linkedNodes: {},
          },
        },
        // 页面级state
        dataset: {
          showInner: {
            dataType: 'boolean',
            initValue: false,
          },
        },
      },
    ],
  },
};
